name: ARM64 Pull and Save Docker Image

on:
  workflow_dispatch:
    inputs:
      docker_image:
        description: '请填写 docker 镜像名:标签'
        required: true
        default: 'mikebrady/shairport-sync:5.0.4或songloft/songloft:2.8.2'

jobs:
  pull_and_package:
    runs-on: ubuntu-latest
    permissions:
      actions: write
      contents: read
    env:
      FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # 直接拉取 1 个镜像并保存
      - name: Pull and Save Image
        run: |
          image="${{ github.event.inputs.docker_image }}"
          
          # 生成安全文件名（替换 / 和 :）
          safe="${image//\//_}"
          safe="${safe//:/-}"
          file="${safe}-arm64.tar"

          echo "====================================="
          echo "镜像：$image"
          echo "保存为：$file"
          echo "====================================="

          docker pull --platform linux/arm64 "$image"
          docker save "$image" -o "$file"

          # 把文件名传给下一步
          echo "file=$file" >> $GITHUB_ENV

      # 官方上传：自动使用镜像名称命名
      - name: Upload Docker Image
        uses: actions/upload-artifact@v4
        with:
          name: （DTB拉取的镜像）${{ env.file }}
          path: ${{ env.file }}
          retention-days: 90

      # 清理
      - name: Clean up
        run: rm -f *.tar
